import Prediction from './project_media/Prediction7312020.jpg'
import Result from './project_media/Results7312020.jpg'
import rycenter from './project_media/Rycenter.JPG'
import cdl from './project_media/portfolio_cdl.JPG'
import nvda from './project_media/nvda.JPG'
import search from './project_media/omnimed.JPG'

const projects = [
    <><h3 className="modalTitle">SAP: Object Detection AI for Grocery Store Discounts</h3><p className="modalText">Consulted by Dr. Campbell of SAP R&D, I am working on ways to reduce company travel costs by validating real-time store discount data. The solution I am developing is an AR mobile application that allows consumers to take pictures of store discounts, have an AI confirm the image, and report the data back to a company representative. I am training a custom YOLOv5 model with a dataset I built from scratch because I plan to publish it as open-source. Currently, there is no data like this on the internet, so I want to give others the chance to tackle this new challenge.</p><div className="imageContainer"><a href="https://www.rycenter.net/"><img src={rycenter} alt="Rycenter homepage" className="modalPicture"/></a></div></>,
    <><h3 className="modalTitle">CDL Highlight Tracker</h3><p className="modalText">I have played video games for as long as I can remember, starting with my uncle's original disk of Starcraft. To have the opportunity to present a demo to a representative at Activision Blizzard was inconceivable. I pitched the idea of having an automated highlight classifier so viewers would not have to sift through a five-hour competition recording. Adding to the project, I developed a way to place the clips onto an interactive map of where the clip occurred in the game. To look at the front-end code, check out my GitHub.</p><div className="imageContainer"><img src={cdl} alt="CDL Highlight Map" className="modalPicture"/></div></>,
    <><h3 className="modalTitle">Medical Search Engine</h3><p className="modalText">Doing freelance work for a client, I worked on developing a medical search engine that could bring up relevant abstracts. Using python to scrape websites for information, I could generate paraphrased information from five articles to a user in 2 seconds or less. I used Django to house the servers and Reactjs to fetch the information on a different port. I also realized that the current medical search engines on the market lack UI design. I made sure to give that area some attention when developing this project.</p><div className="imageContainer"><img src={search} alt="Search Engine Project" className="modalPicture"/></div></>,
    <><h3 className="modalTitle">Rycenter</h3><p className="modalText">Rycenter is a hobby project I created to provide free academic utilities to students during the COVID school years. I wrote four programs for the site: a homework schedule generator, a grammar checker, a final grade calculator, and a semester grade calculator. The homework schedule generator takes the classes you have homework in for the day, classifies if the homework is to study for a test or is an assignment, and then lists what order to finish them in. The grammar checker was my attempt at making a version of Grammarly. It detects past, present, and future tense, contractions, and personal pronouns. The final grade calculator solves inefficiencies I noticed with the original “Roger-Hub” version. With one grade input, it will automatically calculate the bordering letter grades; one input gives all the information a user needs. The semester grade calculator was also in demand, as I noticed people at my school debating their future semester grades on their calculators. This application makes the process of number entry more practical. After half a year, the website maintains an average of 5200 unique monthly users.</p><div className="imageContainer"><a href="https://www.rycenter.net/"><img src={rycenter} alt="Rycenter homepage" className="modalPicture"/></a></div></>,
    <><h3 className="modalTitle">Stock Market Predictions</h3><p className="modalText">I was first introduced to the stock market back in 2016, with my first investment being Nvidia Corporation. Using my experience with data science, I wondered how a predictive model could determine closing stock prices. Using TensorFlow for training the model and scikit-learn’s MinMaxScaler for preprocessing, I created a Long Short Term Memory(LSTM) model to prove my theory. By visualizing my findings in matplotlib, I noticed my model played things on the safer side, as most predictions were slightly below the actual closing price. As no model can achieve perfect accuracy, I am content with this buffer. Staying loyal to my history, I trained my model Nvidia stock data from 2016 to the beginning of 2021. The test data consisted of the rest of the 2021 data. To increase the model’s accuracy, I would need to add in more data from other factors, like a Natural Language Processor(NLP), to scrape article reviews for sentiment analysis.</p><div className="imageContainer"><img src={nvda} alt="NVDA Predictions" className="modalPicture"/></div></>,
    <><h3 className="modalTitle">COVID-19 Case Prediction</h3><p className="modalText">With a new interest in data science, COVID-19 provided a large dataset of opportunities and challenges to solve. I focused on the global COVID-19 cases because there were enough data points at the time to make predictions. To keep high accuracy, I had my model only predict one day into the future. I used a linear regression model after comparing it with other methods like SVR and Lasso. After training the model in July of 2020, my model had missed tomorrow's number by only 98 total cases. This project sparked my interest in data science with the hope of pursuing it as a career while I decide what industry will be the most interesting.</p><div className="imageContainer"><img src={Prediction} alt="Covid predictions" className="prediction"/><img src={Result} alt="Covid cases" className="result"/></div><a href="https://colab.research.google.com/drive/11tUg_KZdjB5wKD9AtpcahQ3wB7kMVx_6?usp=sharing">Google Colab</a></>,
    <><h3 className="modalTitle">Portfolio Website</h3><p className="modalText">This website was honestly a blast to make because I learned how to make 3D models with Blender. I am using Reactjs to run a dependency of react-three-fiber to render in all of the 3D models I created. React will continue to be my choice for full-stack web development for my front-end work.</p></>
];

export default projects;
